name: Z2Y

on:
  repository_dispatch:
    types: [Z T]

jobs:
  DAU:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install
        run: npm install

      - name: Prep URL
        run: |
          echo "${{ github.event.client_payload.zoom_url }}" > urls.txt

      - name: Z R DL
        run: npx --yes zoom-rec-dl@latest

      - name: Y U
        env:
          YOUTUBE_CLIENT_ID: ${{ secrets.YOUTUBE_CLIENT_ID }}
          YOUTUBE_CLIENT_SECRET: ${{ secrets.YOUTUBE_CLIENT_SECRET }}
          YOUTUBE_REFRESH_TOKEN: ${{ secrets.YOUTUBE_REFRESH_TOKEN }}
          VIDEO_TITLE: ${{ github.event.client_payload.title }}
          VIDEO_DESCRIPTION: ${{ github.event.client_payload.description }}
          VIDEO_VISIBILITY: ${{ github.event.client_payload.visibility }}
        run: node upload.js

